#!/bin/bash
set -e

source /home/oracle/.bash_profile 2>/dev/null || true

sqlplus / as sysdba <<SQL
CREATE TABLESPACE SIEBEL_DATA
  DATAFILE '/u01/oradata/SIEBEL/siebel_data01.dbf'
  SIZE 500M AUTOEXTEND ON NEXT 100M MAXSIZE 10G
  EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE SIEBEL_INDEX
  DATAFILE '/u01/oradata/SIEBEL/siebel_index01.dbf'
  SIZE 300M AUTOEXTEND ON NEXT 100M MAXSIZE 5G
  EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE ROLE SSE_ROLE;
GRANT CREATE SESSION TO SSE_ROLE;

CREATE ROLE TBLO_ROLE;
GRANT SSE_ROLE TO TBLO_ROLE;
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER, CREATE SYNONYM, UNLIMITED TABLESPACE TO TBLO_ROLE;

CREATE USER SIEBEL IDENTIFIED BY "siebel2026"
  DEFAULT TABLESPACE SIEBEL_DATA
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON SIEBEL_DATA
  QUOTA UNLIMITED ON SIEBEL_INDEX;

GRANT TBLO_ROLE, SSE_ROLE, CONNECT, RESOURCE, CREATE SESSION, UNLIMITED TABLESPACE TO SIEBEL;
GRANT CREATE PUBLIC SYNONYM, DROP PUBLIC SYNONYM, EXECUTE ON SYS.DBMS_LOCK TO SIEBEL;

CREATE USER SADMIN IDENTIFIED BY "sadmin2026"
  DEFAULT TABLESPACE SIEBEL_DATA
  TEMPORARY TABLESPACE TEMP;

GRANT SSE_ROLE, CONNECT, CREATE SESSION TO SADMIN;

CREATE USER LDAPUSER IDENTIFIED BY "ldabuser2026"
  DEFAULT TABLESPACE SIEBEL_DATA
  TEMPORARY TABLESPACE TEMP;

GRANT SSE_ROLE, CONNECT, CREATE SESSION TO LDAPUSER;

CREATE USER GUESTCST IDENTIFIED BY "guestcst2026"
  DEFAULT TABLESPACE SIEBEL_DATA
  TEMPORARY TABLESPACE TEMP;

GRANT SSE_ROLE, CONNECT, CREATE SESSION TO GUESTCST;

SELECT username, account_status
FROM dba_users
WHERE username IN ('SIEBEL','SADMIN','LDAPUSER','GUESTCST')
ORDER BY 1;
SQL

echo "DB setup done"